require("lntruong.plugins-setup")
require("lntruong.core.options")
require("lntruong.core.keymaps")
require("lntruong.core.colorscheme")
require("lntruong.plugins.comment")
require("lntruong.plugins.nvim-tree")
require("lntruong.plugins.lualine")
require("lntruong.plugins.telescope")
